<?php

namespace Database\Seeders;

use App\Models\Service;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ServiceSeeder extends Seeder
{
    public function run(): void
    {
        $services = [
            // ── Finance ──────────────────────────────────────────────────────
            [
                'title'          => 'Budget Planner',
                'slug'           => 'budget-planner',
                'description'    => 'Track your income and expenses with smart insights for better financial control.',
                'icon'           => '💰',
                'color'          => 'green',
                'route'          => '/budget',
                'category'       => 'finance',
                'requires_auth'  => true,
                'is_active'      => true,
                'sort_order'     => 1,
                'badge'          => null,
                'features'       => [
                    'Monthly budget tracking',
                    'Income vs expense overview',
                    'Priority-based budget items',
                    'Annual financial summary',
                ],
                'modules'        => null,
            ],
            [
                'title'          => 'Income Tracker',
                'slug'           => 'income-tracker',
                'description'    => 'Log and categorize all your income sources in one place.',
                'icon'           => '📈',
                'color'          => 'emerald',
                'route'          => '/income',
                'category'       => 'finance',
                'requires_auth'  => true,
                'is_active'      => true,
                'sort_order'     => 2,
                'badge'          => null,
                'features'       => [
                    'Multiple income sources',
                    'Category-wise breakdown',
                    'Monthly & yearly reports',
                ],
                'modules'        => null,
            ],
            [
                'title'          => 'Expense Manager',
                'slug'           => 'expense-manager',
                'description'    => 'Monitor and control your spending with detailed expense logs.',
                'icon'           => '💳',
                'color'          => 'red',
                'route'          => '/expense',
                'category'       => 'finance',
                'requires_auth'  => true,
                'is_active'      => true,
                'sort_order'     => 3,
                'badge'          => null,
                'features'       => [
                    'Categorized expenses',
                    'Budget vs actual comparison',
                    'Recurring expense tracking',
                ],
                'modules'        => null,
            ],

            // ── Productivity ─────────────────────────────────────────────────
            [
                'title'          => 'Task Manager',
                'slug'           => 'task-manager',
                'description'    => 'Organize your daily activities, assign priorities, and stay productive effortlessly.',
                'icon'           => '📋',
                'color'          => 'blue',
                'route'          => '/tasks',
                'category'       => 'productivity',
                'requires_auth'  => true,
                'is_active'      => true,
                'sort_order'     => 4,
                'badge'          => null,
                'features'       => [
                    'Task categories & tags',
                    'Priority levels',
                    'Recurring tasks & schedules',
                    'Task completion logs',
                ],
                'modules'        => null,
            ],

            // ── Utility ──────────────────────────────────────────────────────
            [
                'title'          => 'Passport & Stamp Photo Maker',
                'slug'           => 'passport-photo-maker',
                'description'    => 'Create passport and stamp-size photos instantly with perfect sizing and clarity.',
                'icon'           => '📸',
                'color'          => 'purple',
                'route'          => '/services/passport-photo-maker',
                'category'       => 'utility',
                'requires_auth'  => false,
                'is_active'      => true,
                'sort_order'     => 5,
                'badge'          => 'Free',
                'features'       => [
                    'Standard passport sizes',
                    'Stamp-size photo output',
                    'Instant download',
                    'Background removal',
                ],
                'modules'        => null,
            ],
            [
                'title'          => 'Registration Service',
                'slug'           => 'registration-service',
                'description'    => 'Seamless registration management for various documents and digital services.',
                'icon'           => '📝',
                'color'          => 'indigo',
                'route'          => '/services/registration-service',
                'category'       => 'utility',
                'requires_auth'  => true,
                'is_active'      => true,
                'sort_order'     => 6,
                'badge'          => null,
                'features'       => [
                    'Document registration',
                    'Digital service enrollment',
                    'Status tracking',
                    'Notification alerts',
                ],
                'modules'        => null,
            ],

            // ── Business ─────────────────────────────────────────────────────
            [
                'title'          => 'Mobile Servicing',
                'slug'           => 'mobile-servicing',
                'description'    => 'Complete mobile repair shop management — job cards, inventory, billing, and customer tracking.',
                'icon'           => '📱',
                'color'          => 'cyan',
                'route'          => '/services/mobile-servicing',
                'category'       => 'business',
                'requires_auth'  => true,
                'is_active'      => true,
                'sort_order'     => 7,
                'badge'          => 'Popular',
                'features'       => [
                    'Job card & repair tracking',
                    'Spare parts inventory',
                    'Customer management',
                    'Invoice & billing',
                    'Technician assignment',
                    'Repair status notifications',
                ],
                'modules'        => [
                    ['name' => 'Job Cards',    'icon' => '🔧', 'desc' => 'Create and track repair job cards from intake to delivery.'],
                    ['name' => 'Inventory',    'icon' => '📦', 'desc' => 'Manage spare parts stock, reorder alerts, and supplier records.'],
                    ['name' => 'Billing',      'icon' => '🧾', 'desc' => 'Generate invoices, accept payments, and track dues.'],
                    ['name' => 'Customers',    'icon' => '👥', 'desc' => 'Maintain customer profiles and repair history.'],
                    ['name' => 'Reports',      'icon' => '📊', 'desc' => 'Daily, weekly, and monthly revenue and job reports.'],
                ],
            ],
            [
                'title'          => 'Restaurant Business',
                'slug'           => 'restaurant-business',
                'description'    => 'Full-featured restaurant management — POS, menu, orders, inventory, and analytics in one platform.',
                'icon'           => '🍽️',
                'color'          => 'orange',
                'route'          => '/services/restaurant-business',
                'category'       => 'business',
                'requires_auth'  => true,
                'is_active'      => true,
                'sort_order'     => 8,
                'badge'          => 'New',
                'features'       => [
                    'Point of Sale (POS)',
                    'Table & order management',
                    'Menu builder',
                    'Kitchen display system',
                    'Inventory & stock control',
                    'Staff & shift management',
                    'Sales analytics & reports',
                ],
                'modules'        => [
                    ['name' => 'POS',           'icon' => '🖥️',  'desc' => 'Fast, touch-friendly point of sale for dine-in, takeaway, and delivery.'],
                    ['name' => 'Menu Manager',  'icon' => '📋',  'desc' => 'Build and update your menu with categories, prices, and images.'],
                    ['name' => 'Orders',        'icon' => '🛎️',  'desc' => 'Real-time order tracking from table to kitchen to delivery.'],
                    ['name' => 'Inventory',     'icon' => '📦',  'desc' => 'Track ingredients, set reorder levels, and reduce wastage.'],
                    ['name' => 'Staff',         'icon' => '👨‍🍳', 'desc' => 'Manage staff roles, shifts, and attendance.'],
                    ['name' => 'Analytics',     'icon' => '📊',  'desc' => 'Revenue, top-selling items, and peak-hour insights.'],
                ],
            ],
            [
                'title'          => 'Resume Builder',
                'slug'           => 'resume-builder',
                'description'    => 'Create professional, ATS-friendly resumes in minutes with smart templates and guided sections.',
                'icon'           => '📄',
                'color'          => 'teal',
                'route'          => '/services/resume-builder',
                'category'       => 'utility',
                'requires_auth'  => true,
                'is_active'      => true,
                'sort_order'     => 9,
                'badge'          => 'New',
                'features'       => [
                    'Professional resume templates',
                    'ATS-optimized formatting',
                    'Step-by-step guided builder',
                    'Multiple export formats (PDF, DOCX)',
                    'Cover letter builder',
                    'Skills & keyword suggestions',
                    'Multiple resume profiles',
                ],
                'modules'        => [
                    ['name' => 'Templates',      'icon' => '🎨', 'desc' => 'Choose from professionally designed, ATS-friendly resume templates.'],
                    ['name' => 'Personal Info',  'icon' => '👤', 'desc' => 'Add your contact details, photo, and professional summary.'],
                    ['name' => 'Experience',     'icon' => '💼', 'desc' => 'List your work history with role, company, dates, and achievements.'],
                    ['name' => 'Education',      'icon' => '🎓', 'desc' => 'Add degrees, certifications, and academic achievements.'],
                    ['name' => 'Skills',         'icon' => '⚡', 'desc' => 'Highlight technical and soft skills with keyword suggestions.'],
                    ['name' => 'Cover Letter',   'icon' => '✉️', 'desc' => 'Generate a tailored cover letter to complement your resume.'],
                    ['name' => 'Export',         'icon' => '📥', 'desc' => 'Download your resume as PDF or DOCX, ready to send.'],
                ],
            ],
            [
                'title'          => 'Website Selling',
                'slug'           => 'website-selling',
                'description'    => 'Launch your online store with ecommerce, product listings, payments, and order management.',
                'icon'           => '🛒',
                'color'          => 'violet',
                'route'          => '/services/website-selling',
                'category'       => 'business',
                'requires_auth'  => true,
                'is_active'      => true,
                'sort_order'     => 10,
                'badge'          => 'New',
                'features'       => [
                    'Product catalog & listings',
                    'Shopping cart & checkout',
                    'Payment gateway integration',
                    'Order & shipping management',
                    'Inventory sync',
                    'Customer accounts',
                    'Discount & coupon engine',
                    'Sales dashboard',
                ],
                'modules'        => [
                    ['name' => 'Ecommerce Store',  'icon' => '🏪',  'desc' => 'Beautiful storefront with product pages, cart, and checkout.'],
                    ['name' => 'POS',              'icon' => '🖥️',  'desc' => 'Sell in-store and online from the same inventory.'],
                    ['name' => 'Inventory',        'icon' => '📦',  'desc' => 'Unified stock management across online and offline channels.'],
                    ['name' => 'Orders',           'icon' => '📬',  'desc' => 'Track, fulfill, and manage customer orders end-to-end.'],
                    ['name' => 'Payments',         'icon' => '💳',  'desc' => 'Accept cards, mobile money, and cash with full reconciliation.'],
                    ['name' => 'Analytics',        'icon' => '📊',  'desc' => 'Conversion rates, revenue trends, and customer insights.'],
                ],
            ],
        ];

        foreach ($services as $data) {
            Service::updateOrCreate(['slug' => $data['slug']], $data);
        }
    }
}
